### ISSUE TITLE
Old session no longer valid, dynamic MRHSession?

### ISSUE THREAD

**Issue by diegoasua** [zrhoffman/svpn-login#5]
Trying to provide sessionid as my organization uses 2FA. As suggested in the configuration instructions I found the cached MRHSession string after logging into the VPN server via browser and then used it for login via svpn. This is the output:

```
Getting params...
Old session no longer valid.
Unable to find the 'Network Access' entry in main menu. Do you have VPN access?
```

I went back to the VPN server url in my explorer and checked the sessionid again and it was different. It seems that I am assigned a different one every time I log in. Is this normal?

**Comment by zrhoffman** [comment]
Yep, different session ID every time you log in. If you find a more efficient way, let me know.

**Comment by diegoasua** [comment]
Thanks!
